In [ ]:
import pandas as pd
import sys
import os

# 모든 행과 열을 표시하도록 설정
pd.set_option('display.max_rows', None)  # 모든 행 표시
pd.set_option('display.max_columns', None)  # 모든 열 표시
pd.set_option('display.width', None)  # 출력 너비 제한 해제
pd.set_option('display.max_colwidth', None)  # 열 너비 제한 해제

In [3]:
# 현재 작업 디렉토리 확인
print("현재 작업 디렉토리:", os.getcwd())

현재 작업 디렉토리: /home/sam/projects/Project_Curation/src/analysis

In [9]:
# 상위 디렉토리로 이동하여 data 폴더에 접근
data2025 = pd.read_csv('../../data/ReadingLog-2025.csv')
data2024 = pd.read_csv('../../data/ReadingLog-2024.csv')
data2023 = pd.read_csv('../../data/ReadingLog-2023.csv')

In [10]:
# data2024를 row 158까지 분할하여 실제 데이터만 추출
data2024_filtered = data2024.iloc[:158]

# 분할된 데이터 확인
print(f"원본 데이터 shape: {data2024.shape}")
print(f"필터링된 데이터 shape: {data2024_filtered.shape}")
print(f"마지막 행 인덱스: {data2024_filtered.index[-1]}")

# 필터링된 데이터 미리보기
data2024_filtered.tail()

원본 데이터 shape: (322, 10)
필터링된 데이터 shape: (158, 10)
마지막 행 인덱스: 157

,Month Completed,#,Book Title,Author,Pages/Word Count/Parts,Type,Trope,Rating,Spice,Summary/Notes
153,December,154.0,"You, Again",Kate Goldbeck,448,Book (P),Enemies to Lovers,⭐⭐⭐⭐,💓,i read half of this in november but didn't fin...
154,December,155.0,The Fiancee Dilemma,Elena Armas,410,Book (P),Fake Dating,⭐⭐⭐⭐,💓💓,this was very cheesy and enjoyable i wish ther...
155,December,156.0,Next of Kin,Hannah Bonam Young,395,Book (P),Forced Proximity,⭐⭐⭐,💓💓,"cute, but i was expecting a little more, but i..."
156,December,157.0,Collide,Bal Khabra,295,Book (P),Sports Romance,⭐⭐⭐,💓💓🤮,stop trying to replicate garret graham it can'...
157,December,158.0,A Novel Love Story,Ashley Poston,385,Book (P),Paranormal,⭐⭐⭐,💓,i was a little disappointed; i loved her other...

In [11]:
data2023_filtered = data2023.iloc[:60]

# 분할된 데이터 확인
print(f"원본 데이터 shape: {data2023.shape}")
print(f"필터링된 데이터 shape: {data2023_filtered.shape}")
print(f"마지막 행 인덱스: {data2023_filtered.index[-1]}")

# 필터링된 데이터 미리보기
data2023_filtered.tail()

원본 데이터 shape: (107, 10)
필터링된 데이터 shape: (60, 10)
마지막 행 인덱스: 59

,Month Completed,#,Book Title,Author,Pages/Word Count/Parts,Type,Trope,Rating,Spice,Summary
55,December,56.0,Bloodied Machine,-,"2,206 words",Fic (ao3),onceler,no,🤮,no i will not talk about.
56,December,57.0,Driving with Devil,objectlesson,"11,193 words",Fic (ao3),cars,no,🤮,i refuse to watch cars again.
57,December,58.0,you're a reporter and you interview the oncele...,waxponds,"3,177 words",Fic (ao3),onceler,⭐⭐⭐,💓💓🤮,"this was fun, but i will not go into detail."
58,December,59.0,The Fine Print,Lauren Asher,442 Pages,Book (K),Workplace Romance,⭐⭐,💓💓🤮,I finally finished this freaking series even t...
59,December,60.0,Even If This Love Disappears Tonight,Misaki Ichijo,236,Book (P),Grief/Loss,⭐⭐⭐⭐,😇,This is basically Anterograde Tomorrow. It is ...

In [12]:
data2025_filtered = data2025.iloc[:12]

# 분할된 데이터 확인
print(f"원본 데이터 shape: {data2025.shape}")
print(f"필터링된 데이터 shape: {data2025_filtered.shape}")
print(f"마지막 행 인덱스: {data2025_filtered.index[-1]}")

# 필터링된 데이터 미리보기
data2025_filtered.tail()

원본 데이터 shape: (216, 10)
필터링된 데이터 shape: (12, 10)
마지막 행 인덱스: 11

,Unnamed: 0,#,Book Title,Author,Pages,Type,Trope,Rating,Spice,Notes
7,June,8.0,Rewind It Back,Liz Tomforde,491.0,Book (K),Second Chance,⭐⭐⭐⭐⭐,💓💓,rio is perfect and i am in love with him
8,June,9.0,Gloves Off,Stephanie Archer,464.0,Book (K),Marriage of Convenienc/Arranged Marriage,⭐⭐⭐⭐,💓💓💓,little frustrating with all the miscommunicati...
9,June,10.0,Broken Harbor,Catherine Cowles,403.0,Book (K),Single Parent,⭐⭐⭐⭐,💓💓💓,every book in this series has the same structu...
10,June,11.0,Beautiful Exile,Catherine Cowles,402.0,Book (K),Brother's Best Friend,⭐⭐⭐⭐,💓💓💓,I FUCKING CALLED THE PLOT TWIST... but i reall...
11,June,12.0,Seven Year Itch,Amy Daws,372.0,Book (K),Enemies with Benefits,⭐⭐⭐,💓💓💓💓,this book was so slutty i felt like i had to s...

In [13]:
print(data2025_filtered.shape)
print(data2024_filtered.shape)
print(data2023_filtered.shape)

(12, 10)
(158, 10)
(60, 10)

In [14]:
print(f"user's read books count:{12+158+60}")

user's read books count:230

In [15]:
# print(data2024.columns)


# 방법 1: drop() 메서드 사용 (원본 데이터 변경하지 않음)
columns_to_drop = ['#', 'Month Completed', 'Pages/Word Count/Parts', 'Spice']  # 제거하고 싶은 컬럼들
data2024_cleaned = data2024_filtered.drop(columns=columns_to_drop)


# 결과 확인
print("원본 컬럼:", data2024_filtered.columns.tolist())
print("정리된 컬럼:", data2024_cleaned.columns.tolist())

data2024_cleaned.head()

원본 컬럼: ['Month Completed', '#', 'Book Title', 'Author', 'Pages/Word Count/Parts', 'Type', 'Trope', 'Rating', 'Spice', 'Summary/Notes']
정리된 컬럼: ['Book Title', 'Author', 'Type', 'Trope', 'Rating', 'Summary/Notes']

,Book Title,Author,Type,Trope,Rating,Summary/Notes
0,Too Much,I.A. Dice,Book (K),Friends to Lovers,⭐⭐⭐,Thalia has recently moved to Newport Beach to ...
1,Too Wrong,I.A. Dice,Book (K),Second Chance,⭐⭐,"Three years ago, Cassidy and Logan hooked up a..."
2,Too Sweet,I.A. Dice,Book (K),GrumpyxSunshine,⭐⭐⭐,Nico is the most intimidating of the Hayes bro...
3,Too Strong,I.A. Dice,Book (K),Small Town,⭐⭐⭐,Conor is instantly in love with Vee when he me...
4,Too Hard,I.A. Dice,Book (K),Enemies to Lovers,⭐⭐⭐⭐,Cody moves into his new apartment which happen...

In [16]:
# print(data2025.columns)
columns_to_drop = ["Unnamed: 0", "#", "Pages", 'Spice']
data2025_cleaned = data2025_filtered.drop(columns=columns_to_drop)

print("원본 컬럼:", data2025_filtered.columns.tolist())
print("정리된 컬럼:", data2025_cleaned.columns.tolist())

data2025_cleaned.head()

원본 컬럼: ['Unnamed: 0', '#', 'Book Title', 'Author', 'Pages', 'Type', 'Trope', 'Rating', 'Spice', 'Notes']
정리된 컬럼: ['Book Title', 'Author', 'Type', 'Trope', 'Rating', 'Notes']

,Book Title,Author,Type,Trope,Rating,Notes
0,Better than the Movies,Lynn Painter,Book (P),Enemies to Lovers,⭐⭐⭐⭐⭐,cute fluffy perfect romcom vibes; sometimes th...
1,Nothing Like the Movies,Lynn Painter,Book (P),Second Chance,⭐⭐⭐⭐,sequel to Better than the Movies; it sucks tha...
2,Daydream,Hannah Grace,Book (P),Friends to Lovers,⭐⭐⭐⭐⭐,"so cute and fluffy, but also i feel like it wa..."
3,The Love Wager,Lynn Painter,Book (P),Friends to Lovers,⭐⭐⭐⭐,i forgot to updat ethis. it was really cute an...
4,The Charlie Method,Elle Kennedy,Book (K),Friends with Benefits,⭐⭐⭐,throuple

In [17]:
print(data2023.columns)
columns_to_drop = ['#', 'Month Completed', 'Pages/Word Count/Parts', 'Spice']
data2023_cleaned = data2023_filtered.drop(columns=columns_to_drop)

print("원본 컬럼:", data2023_filtered.columns.tolist())
print("정리된 컬럼:", data2023_cleaned.columns.tolist())
data2023_cleaned.head()

Index(['Month Completed', '#', 'Book Title', 'Author',
       'Pages/Word Count/Parts', 'Type', 'Trope', 'Rating', 'Spice',
       'Summary'],
      dtype='object')
원본 컬럼: ['Month Completed', '#', 'Book Title', 'Author', 'Pages/Word Count/Parts', 'Type', 'Trope', 'Rating', 'Spice', 'Summary']
정리된 컬럼: ['Book Title', 'Author', 'Type', 'Trope', 'Rating', 'Summary']

,Book Title,Author,Type,Trope,Rating,Summary
0,Hobi's Demands,Crimson_Bubbles,Fic (W),Dom/Sub,⭐⭐⭐⭐,YN is a nanny for Hobi's niece. They enter int...
1,Jin's Mistake,Crimson_Bubbles,Fic (W),Marriage of Convenienc/Arranged Marriage,⭐⭐⭐,Jin and YN are dating but he says he can't mar...
2,Temporary Bliss,jjkthclub,Fic (W),Fake Dating,⭐⭐,Y/n has a crush on Tae and decides to fake dat...
3,His Contracted Spouse,money_ichoose,Fic (W),Second Chance,⭐,This whole thing is pretty just martial rape. ...
4,The Dark Filter,June_writes,Fic (ao3),omegaverse gangbang,no,i don't want to talk about it. there are too m...

# 후처리 시작

In [18]:
# 함수 파트

# 별점을 숫자로 변환하는 함수 정의
def convert_rating_to_numeric(rating):
    """
    별점 문자열을 숫자로 변환하는 함수
    
    Args:
        rating (str): 별점 문자열 (예: "⭐⭐⭐⭐", "⭐⭐⭐")
        
    Returns:
        int: 변환된 숫자 (1-5)
    """
    rating_mapping = {
        '⭐': 1,
        '⭐⭐': 2,
        '⭐⭐⭐': 3,
        '⭐⭐⭐⭐': 4,
        '⭐⭐⭐⭐⭐': 5
    }
    return rating_mapping.get(rating, 0)  # 매핑되지 않은 경우 0 반환

In [19]:
print(data2025_cleaned['Rating'].value_counts(), "\n")
print(data2024_cleaned['Rating'].value_counts(), "\n")
print(data2023_cleaned['Rating'].value_counts(), "\n")



# Rating 컬럼을 숫자로 변환
data2024_cleaned['Rating_Numeric'] = data2024_cleaned['Rating'].apply(convert_rating_to_numeric)
data2023_cleaned['Rating_Numeric'] = data2023_cleaned['Rating'].apply(convert_rating_to_numeric)
data2025_cleaned['Rating_Numeric'] = data2025_cleaned['Rating'].apply(convert_rating_to_numeric)

# 변환 결과 확인
print("변환된 별점 분포:")
print("2025년:", data2025_cleaned['Rating_Numeric'].value_counts().sort_index())
print("2024년:", data2024_cleaned['Rating_Numeric'].value_counts().sort_index())
print("2023년:", data2023_cleaned['Rating_Numeric'].value_counts().sort_index())

Rating
⭐⭐⭐⭐     7
⭐⭐⭐⭐⭐    3
⭐⭐⭐      2
Name: count, dtype: int64

Rating
⭐⭐⭐⭐     74
⭐⭐⭐      47
⭐⭐⭐⭐⭐    28
⭐⭐        7
⭐         2
Name: count, dtype: int64

Rating
⭐⭐⭐      27
⭐⭐⭐⭐     12
⭐⭐       10
⭐         4
⭐⭐⭐⭐⭐     4
no        3
Name: count, dtype: int64

변환된 별점 분포:
2025년: Rating_Numeric
3    2
4    7
5    3
Name: count, dtype: int64
2024년: Rating_Numeric
1     2
2     7
3    47
4    74
5    28
Name: count, dtype: int64
2023년: Rating_Numeric
0     3
1     4
2    10
3    27
4    12
5     4
Name: count, dtype: int64

In [20]:
# 방법 1: drop() 메서드 사용 (원본 데이터 변경하지 않음)
column_to_drop = ["Rating"]
data2025_cleaned = data2025_cleaned.drop(columns=column_to_drop)
data2024_cleaned = data2024_cleaned.drop(columns=column_to_drop)
data2023_cleaned = data2023_cleaned.drop(columns=column_to_drop)


# 결과 확인
print("정리된 컬럼:", data2025_cleaned.columns.tolist() ,"\n")

print("정리된 컬럼:", data2024_cleaned.columns.tolist() ,"\n")

print("정리된 컬럼:", data2023_cleaned.columns.tolist() ,"\n")

정리된 컬럼: ['Book Title', 'Author', 'Type', 'Trope', 'Notes', 'Rating_Numeric']

정리된 컬럼: ['Book Title', 'Author', 'Type', 'Trope', 'Summary/Notes', 'Rating_Numeric']

정리된 컬럼: ['Book Title', 'Author', 'Type', 'Trope', 'Summary', 'Rating_Numeric']

In [21]:
data2025_cleaned['Trope'].value_counts()

Trope
Second Chance                               2
Friends to Lovers                           2
Enemies to Lovers                           1
Friends with Benefits                       1
Romantasy                                   1
Fake Dating                                 1
Marriage of Convenienc/Arranged Marriage    1
Single Parent                               1
Brother's Best Friend                       1
Enemies with Benefits                       1
Name: count, dtype: int64

In [22]:
data2024_cleaned['Trope'].value_counts()

Trope
Dark Romance                                33
Sports Romance                              16
Romantasy                                   13
Friends to Lovers                           10
Fake Dating                                 10
Single Parent                                9
Forced Proximity                             8
GrumpyxSunshine                              6
Enemies to Lovers                            6
Workplace Romance                            6
Marriage of Convenienc/Arranged Marriage     5
Second Chance                                5
Small Town                                   5
Brother's Best Friend                        4
BDSM                                         4
Forbidden                                    4
Accidental Pregnancy                         3
Non-romance                                  2
Billionaire                                  2
Paranormal                                   2
Time Travel                                  1
Thriller                                     1
Best Friend's Brother                        1
Friends with Benefits                        1
Enemies with Benefits                        1
Name: count, dtype: int64

In [23]:
data2023_cleaned['Trope'].value_counts()

Trope
Marriage of Convenienc/Arranged Marriage    5
Fake Dating                                 5
Second Chance                               5
Brother's Best Friend                       4
Celebrity                                   4
Friends to Lovers                           3
Enemies to Lovers                           3
Neighbors                                   2
Established Relationship                    2
Workplace Romance                           2
Best Friend's Brother                       2
Soulmate AU                                 2
onceler                                     2
Enemies with Benefits                       2
Grief/Loss                                  2
Friends with Benefits                       2
Royalty                                     2
Small Town                                  1
omegaverse gangbang                         1
Dom/Sub                                     1
Tattoo Artist                               1
Fairy Tale AU                               1
Time Travel                                 1
Failed One Night Stand                      1
Friendship/Platonic Soulmates               1
Forced Proximity                            1
Billionaire                                 1
cars                                        1
Name: count, dtype: int64

In [29]:
data2024_cleaned.head()

,Book Title,Author,Type,Trope,Summary/Notes,Rating_Numeric
0,Too Much,I.A. Dice,Book (K),Friends to Lovers,"Thalia has recently moved to Newport Beach to get a fresh start after escaping her home country of Greece. She meets Theo and they instantly want to bang each other. He is the fuck and forget type, but she is too fun of a friend to lose. They end up moving in with each other and she is constantly trying to get his attention and he is constantly jerking it in private. Anyway they eventually bang and start dating. Thalia is falling in love, but is worried he will leave her when he finds out her secret: she killed her husband in Greece. While they are also dealing with a break-in she tells him her secret. He does flip out and doesn't even ask questions. He is pissed that she was married and doesn't even care about the murder part. Anyway, she did in fact murder her husband who was famous politician and that is because he was a child molester. Anyway, they make up and in the end Theo proposes. HEA. Unhinged. Oh my freaking god unhinged. Literally, things just kept happening and I was like wtf the whole time. so fun.",3
1,Too Wrong,I.A. Dice,Book (K),Second Chance,"Three years ago, Cassidy and Logan hooked up and they were instantly into each other. However, once he found out that she had already slept with his brother (she didn't know it was his brother) he broke it up and treated her coldly. Now in the present, after she almost drowns at a party and he saves her. The two are drawn together. Cass is in love with him and will do anything to just spend time with him. They enter into a friends with benefits situation when they both secretly want more. Logan is worried though that his brothers will hate him if he gets with her since she slept with Theo (who is now happily married) and is best friends with Kaya who cheated on their other brother Nico. They ""break up"" several times and after Cass is in a car accident Logan pulls his head out of his ass and decides he wants to be with her. At the same time, Cass finds out she is pregnant, but is worried how Logan will react. Logan comes over and Cass tells him the news and he tells her he came over to tell her that he wants to be with her. They move in together and HEA. Honestly, I dislike Logan. Like Cass shares her trauma with him pretty early and like she has severe abandonment issues and no one has ever told her ""i love you"" and he keeps kicking her to the curb and treating her like shit and then getting jealous when she looks at someone else. no thank you sir.",2
2,Too Sweet,I.A. Dice,Book (K),GrumpyxSunshine,"Nico is the most intimidating of the Hayes brothers. He is tall, dark, tattooed and possessive. Mia is soft, short and young--definitely not his type. However, he can't help but feel himself pulled toward her. He wants her, but Cody has already claimed her that means he can't have her. He would never betray his brother like that. Mia wants Nico, but she's too insecure. Anyway, opposites attract and they are brought together. She wants someone to take care of her and lead her and Nico wants someone he can take care of. A match made in heaven. This fic is sweet, spicy and just the right amount of slowburn. There is no third act break up (Hallelujah!). The age gap does give me the ick though. She is 19 and he is 29. It's just a little too much, but if I ignore it it's fine. Also trigger warning for bullying and SA.",3
3,Too Strong,I.A. Dice,Book (K),Small Town,"Conor is instantly in love with Vee when he meets her at his Halloween party. However, Vee is wary of him because she thinks he is just another rich douchebag. He constantly pursues her and is the opposite of everything she is expecting. He is obsessed and devoted to her. She is still nervous though because her dad hates his dad. When she tells her father she is dating Conor, he says that she can't because Conor is her brother. Dun Dun Dun. He's not, the dad is lying. Her half-sister isn't actually her half-sister, she is Conor's half-sister--the result of Conor's dad having an affair. The happy couple is back together and the seven brothers confront their dad, but everyone is happy to finally have a girl in the family. Loved Conor, this book was great until the half-sibling cheating plot. Just why was that necessary. This book would've been four stars if not for that twist.",3
4,Too Hard,I.A. Dice,Book (K),Enemies to Lovers,"Cody moves into his new apartment which happens to be across from Blair--the girl he hates because she bullied Mia. Anyway, you know hate leads to sex and sex leads to feelings and Blair isn't a bad person she is just really fucking traumatized. Overall this book I think has the most well-rounded plot. The only insane plot twist is at the end of the epilogue when we are left with the cliffhanger of Colt being in a car accident. Also, it says it is enemies to lovers, but only Cody really hates Blair. Blair actually had a crush on Cody through most of high school and college.",4

In [32]:
data2023_cleaned['Trope']

# 특정 키워드가 포함된 행들을 필터링하여 확인
keywords = ['onceler', 'omegaverse', 'gangbang', 'Dom/Sub', 'cars']

# 각 연도별 데이터에서 키워드가 포함된 행들을 찾기
for year, data in [('2025', data2025_cleaned), ('2024', data2024_cleaned), ('2023', data2023_cleaned)]:
    print(f"\n=== {year}년 데이터에서 키워드가 포함된 행들 ===")
    
    # 키워드가 포함된 행들을 찾기
    filtered_rows = data[data['Trope'].str.contains('|'.join(keywords), case=False, na=False)]
    
    if len(filtered_rows) > 0:
        print(f"총 {len(filtered_rows)}개 행 발견:")
        for idx, row in filtered_rows.iterrows():
            print(f"  - {row['Book Title']} | {row['Author']} | {row['Trope']} | {row['Rating_Numeric']}점")
    else:
        print("해당 키워드가 포함된 행이 없습니다.")

=== 2025년 데이터에서 키워드가 포함된 행들 ===
해당 키워드가 포함된 행이 없습니다.

=== 2024년 데이터에서 키워드가 포함된 행들 ===
해당 키워드가 포함된 행이 없습니다.

=== 2023년 데이터에서 키워드가 포함된 행들 ===
총 5개 행 발견:
  - Hobi's Demands | Crimson_Bubbles | Dom/Sub | 4점
  - The Dark Filter | June_writes | omegaverse gangbang | 0점
  - Bloodied Machine | - | onceler | 0점
  - Driving with Devil | objectlesson | cars | 0점
  - you're a reporter and you interview the onceler in this one | waxponds | onceler | 3점

In [34]:
# 키워드가 포함된 행들을 찾아서 삭제
rows_to_remove = data2023_cleaned[data2023_cleaned['Trope'].str.contains('|'.join(keywords), case=False, na=False)]

print(f"삭제할 행 수: {len(rows_to_remove)}")
print("삭제할 행들:")
for idx, row in rows_to_remove.iterrows():
    print(f"  - {row['Book Title']} | {row['Author']} | {row['Trope']}")

# 해당 행들을 삭제
data2023_cleaned = data2023_cleaned[~data2023_cleaned['Trope'].str.contains('|'.join(keywords), case=False, na=False)]

print(f"\n삭제 후 데이터 크기: {data2023_cleaned.shape}")
print(f"삭제 전 크기와 비교: {len(data2023_cleaned) + len(rows_to_remove)} -> {len(data2023_cleaned)}")

삭제할 행 수: 0
삭제할 행들:

삭제 후 데이터 크기: (55, 6)
삭제 전 크기와 비교: 55 -> 55

In [38]:
# 컬럼삭제
data2025_cleaned.drop(columns=['Type'], inplace=True)
data2024_cleaned.drop(columns=['Type'], inplace=True)
data2023_cleaned.drop(columns=['Type'], inplace=True)

Index(['Book Title', 'Author', 'Type', 'Trope', 'Notes', 'Rating_Numeric'], dtype='object')
Index(['Book Title', 'Author', 'Type', 'Trope', 'Summary/Notes',
       'Rating_Numeric'],
      dtype='object')
Index(['Book Title', 'Author', 'Type', 'Trope', 'Summary', 'Rating_Numeric'], dtype='object')

Index(['Book Title', 'Author', 'Trope', 'Summary', 'Rating_Numeric'], dtype='object')

In [39]:
print(data2025_cleaned.columns)
print(data2024_cleaned.columns)
print(data2023_cleaned.columns)

Index(['Book Title', 'Author', 'Trope', 'Notes', 'Rating_Numeric'], dtype='object')
Index(['Book Title', 'Author', 'Trope', 'Summary/Notes', 'Rating_Numeric'], dtype='object')
Index(['Book Title', 'Author', 'Trope', 'Summary', 'Rating_Numeric'], dtype='object')

In [41]:
# 딕셔너리로 여러 컬럼 한번에 변경
data2025_cleaned.rename(columns={'Rating_Numeric': 'Rating'}, inplace=True)
data2024_cleaned.rename(columns={'Rating_Numeric': 'Rating', 'Summary/Notes': 'Notes'}, inplace=True)
data2023_cleaned.rename(columns={'Rating_Numeric': 'Rating', 'Summary' : 'Notes'}, inplace=True)

print("\n" + "="*50)

orders = ['Book Title', 'Author', 'Trope', 'Rating', 'Notes']
data2025_cleaned = data2025_cleaned[orders]
data2024_cleaned = data2024_cleaned[orders]
data2023_cleaned = data2023_cleaned[orders]

print(data2025_cleaned.columns)
print(data2024_cleaned.columns)
print(data2023_cleaned.columns)

2. 여러 컬럼 한번에 변경:

==================================================

=== 컬럼 순서 바꾸는 방법들 ===
Index(['Book Title', 'Author', 'Trope', 'Rating', 'Notes'], dtype='object')
Index(['Book Title', 'Author', 'Trope', 'Rating', 'Notes'], dtype='object')
Index(['Book Title', 'Author', 'Trope', 'Rating', 'Notes'], dtype='object')

In [45]:
data2025_cleaned.to_csv('../../data/data2025_cleaned.csv', index=False)
data2024_cleaned.to_csv('../../data/data2024_cleaned.csv', index=False)
data2023_cleaned.to_csv('../../data/data2023_cleaned.csv', index=False)